// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AndroidSvg: typeof import('./.vitepress/vitepress/components/home/svg/android-svg.vue')['default']
    Dark: typeof import('./.vitepress/vitepress/components/icons/dark.vue')['default']
    HomeCards: typeof import('./.vitepress/vitepress/components/home/home-cards.vue')['default']
    IosSvg: typeof import('./.vitepress/vitepress/components/home/svg/ios-svg.vue')['default']
    IRiExternalLinkLine: typeof import('~icons/ri/external-link-line')['default']
    LeftBottomLayerSvg: typeof import('./.vitepress/vitepress/components/home/svg/left-bottom-layer-svg.vue')['default']
    LeftLayerSvg: typeof import('./.vitepress/vitepress/components/home/svg/left-layer-svg.vue')['default']
    Light: typeof import('./.vitepress/vitepress/components/icons/light.vue')['default']
    MicroServiceSvg: typeof import('./.vitepress/vitepress/components/home/svg/micro-service-svg.vue')['default']
    ParallaxHome: typeof import('./.vitepress/vitepress/components/globals/parallax-home.vue')['default']
    RightBottomLayerRapidsSvg: typeof import('./.vitepress/vitepress/components/home/svg/right-bottom-layer-rapids-svg.vue')['default']
    RightBottomLayerSvg: typeof import('./.vitepress/vitepress/components/home/svg/right-bottom-layer-svg.vue')['default']
    RightLayerMoonSvg: typeof import('./.vitepress/vitepress/components/home/svg/right-layer-moon-svg.vue')['default']
    RightLayerSunSvg: typeof import('./.vitepress/vitepress/components/home/svg/right-layer-sun-svg.vue')['default']
    ScreenSvg: typeof import('./.vitepress/vitepress/components/home/svg/screen-svg.vue')['default']
    ToggleButton: typeof import('./.vitepress/vitepress/components/icons/toggle-button.vue')['default']
    ToggleSidebarBtn: typeof import('./.vitepress/vitepress/components/subnav/toggle-sidebar-btn.vue')['default']
    VersionTag: typeof import('./.vitepress/vitepress/components/dev/VersionTag.vue')['default']
    VpApp: typeof import('./.vitepress/vitepress/components/vp-app.vue')['default']
    VpContent: typeof import('./.vitepress/vitepress/components/vp-content.vue')['default']
    VpDemo: typeof import('./.vitepress/vitepress/components/vp-demo.vue')['default']
    VpDocContent: typeof import('./.vitepress/vitepress/components/vp-doc-content.vue')['default']
    VpExample: typeof import('./.vitepress/vitepress/components/demo/vp-example.vue')['default']
    VpHamburger: typeof import('./.vitepress/vitepress/components/navbar/vp-hamburger.vue')['default']
    VpHeroContent: typeof import('./.vitepress/vitepress/components/vp-hero-content.vue')['default']
    VpLink: typeof import('./.vitepress/vitepress/components/common/vp-link.vue')['default']
    VpMenu: typeof import('./.vitepress/vitepress/components/navbar/vp-menu.vue')['default']
    VpMenuLink: typeof import('./.vitepress/vitepress/components/navbar/vp-menu-link.vue')['default']
    VpNav: typeof import('./.vitepress/vitepress/components/vp-nav.vue')['default']
    VpNavbar: typeof import('./.vitepress/vitepress/components/vp-navbar.vue')['default']
    VpNavFull: typeof import('./.vitepress/vitepress/components/vp-nav-full.vue')['default']
    VpNotFound: typeof import('./.vitepress/vitepress/components/vp-not-found.vue')['default']
    VpOverlay: typeof import('./.vitepress/vitepress/components/vp-overlay.vue')['default']
    VpPageNav: typeof import('./.vitepress/vitepress/components/doc-content/vp-page-nav.vue')['default']
    VpSearch: typeof import('./.vitepress/vitepress/components/navbar/vp-search.vue')['default']
    VpSidebar: typeof import('./.vitepress/vitepress/components/vp-sidebar.vue')['default']
    VpSidebarLink: typeof import('./.vitepress/vitepress/components/sidebar/vp-sidebar-link.vue')['default']
    VpSocialLink: typeof import('./.vitepress/vitepress/components/navbar/vp-social-link.vue')['default']
    VpSocialLinks: typeof import('./.vitepress/vitepress/components/navbar/vp-social-links.vue')['default']
    VpSourceCode: typeof import('./.vitepress/vitepress/components/demo/vp-source-code.vue')['default']
    VpSubnav: typeof import('./.vitepress/vitepress/components/vp-subnav.vue')['default']
    VpSwitch: typeof import('./.vitepress/vitepress/components/common/vp-switch.vue')['default']
    VpTableOfContent: typeof import('./.vitepress/vitepress/components/doc-content/vp-table-of-content.vue')['default']
    VpThemeToggler: typeof import('./.vitepress/vitepress/components/navbar/vp-theme-toggler.vue')['default']
    Vue3Svg: typeof import('./.vitepress/vitepress/components/home/svg/vue3-svg.vue')['default']
  }
}

export {}
